services:
  db:
    image: postgres:16-alpine

    container_name: bookstore_db

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .

    container_name: bookstore_web

    env_file:
      - .env

    ports:
      - "8001:8000"

    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/static

#    command: >
#      sh -c "python manage.py migrate &&
#      python manage.py runserver 0.0.0.0:8000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  media_data:
  static_data: