services:
  web:
    build: .

    container_name: bookstore_web

    env_file:
      - .env

    ports:
      - "8001:8000"

    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles

    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  media_data:
  static_data: