# Generated by Django 6.1 on 2026-09-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='books/blank.jpg', null=True, upload_to='books/'),
        ),
    ]
