# Generated by Django 6.1 on 2026-08-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_description_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
